import { EntitySchema } from "typeorm";

export const Shop = new EntitySchema({
  name: "Shop",
  tableName: "shops",
  columns: {
    id: { type: "uuid", primary: true, generated: "uuid" },
    ownerId: { type: "uuid", name: "owner_id" },
    name: { type: "varchar", length: 150 },
    slug: { type: "varchar", length: 180, unique: true, nullable: true },
    description: { type: "text", nullable: true },
    categoryId: { type: "uuid", nullable: true, name: "category_id" },
    phone: { type: "varchar", length: 15, nullable: true },
    email: { type: "varchar", length: 150, nullable: true },
    address: { type: "text", nullable: true },
    city: { type: "varchar", length: 100, nullable: true },
    state: { type: "varchar", length: 100, nullable: true },
    pincode: { type: "varchar", length: 10, nullable: true },
    lat: { type: "decimal", precision: 10, scale: 7, nullable: true },
    lng: { type: "decimal", precision: 10, scale: 7, nullable: true },
    location: {
      type: "geography",
      spatialFeatureType: "Point",
      srid: 4326,
      nullable: true,
    },
    openingTime: { type: "time", nullable: true, name: "opening_time" },
    closingTime: { type: "time", nullable: true, name: "closing_time" },
    isOpen: { type: "boolean", default: false, name: "is_open" },
    isApproved: { type: "boolean", default: false, name: "is_approved" },
    rating: { type: "decimal", precision: 3, scale: 2, default: 0 },
    totalReviews: { type: "int", default: 0, name: "total_reviews" },
    deliveryTime: { type: "varchar", length: 50, nullable: true, name: "delivery_time" },
    minOrder: { type: "decimal", precision: 10, scale: 2, default: 0, name: "min_order" },
    shopImage: { type: "varchar", length: 500, nullable: true, name: "shop_image" },
    bannerImage: { type: "varchar", length: 500, nullable: true, name: "banner_image" },
    logoImage: { type: "varchar", length: 500, nullable: true, name: "logo_image" },
    createdAt: { type: "timestamptz", createDate: true, name: "created_at" },
    updatedAt: { type: "timestamptz", updateDate: true, name: "updated_at" },
  },
  relations: {
    owner: { type: "many-to-one", target: "User", joinColumn: { name: "owner_id" }, onDelete: "CASCADE" },
    category: { type: "many-to-one", target: "Category", joinColumn: { name: "category_id" }, nullable: true, onDelete: "SET NULL" },
  },
});
